package com.senacor.lpt.service.creditapplication.repository

import com.google.cloud.spring.data.firestore.FirestoreReactiveRepository

interface CreditApplicationRepository : FirestoreReactiveRepository<CreditApplicationFirestoreModel>