apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-master-data

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml

configMapGenerator:
  - name: responses-config
    files:
      - ../base/luke_response.json