apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lpt-backend-config
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 5
    type: HTTP
    requestPath: /actuator/health
    port: 8080