apiVersion: apps/v1
kind: Deployment
metadata:
  name: creditapplication-service-deployment
  labels:
    app: creditapplication-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: creditapplication-service
  template:
    metadata:
      labels:
        app: creditapplication-service
    spec:
      serviceAccountName: creditapplication-service-sa
      containers:
        - name: creditapplication-service
          image: europe-west1-docker.pkg.dev/vbdev-436712/lpt/creditapplication-service:0.0.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1000m"
            limits:
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /status
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 20
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
