apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: creditapplication-ingress
spec:
  defaultBackend:
    service:
      name: creditapplication-k8s-service
      port:
        number: 8080