apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lpt

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - backend-config.yaml
  - spring.serviceMonitor.yaml

images:
  - name: europe-west1-docker.pkg.dev/vbdev-436712/lpt/creditapplication-service
    newTag: "$IMAGE_TAG_TO_DEPLOY"

configMapGenerator:
  - name: application-config
    files:
      - application.yaml