apiVersion: v1
kind: Service
metadata:
  name: creditapplication-service
  labels:
    app: creditapplication-service
spec:
  selector:
    app: creditapplication-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080