apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customer-master-data

resources:
  - ../base

configMapGenerator:
  - name: mappings-config
    files:
      - mappings.json