name: Build and push to GAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
#
#      # TODO: What is this step doing anyway?
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0

      - name: Build Docker image with pack
        run: |
          pack build tmp --builder gcr.io/buildpacks/builder --env GOOGLE_RUNTIME_VERSION=17
        env:
      # TODO: evaluate if we need these
          PACK_NO_COLOR: true  # Optional: disable color output
          DOCKER_BUILDKIT: 1   # Optional: enable BuildKit for better performance

      - name: Google auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.AUTOMATION_SA_KEY_JSON }}

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.AUTOMATION_SA_KEY_JSON }}

      - name: Build docker image name
        run: |
          PROJECT_NAME=$( ./gradlew properties |  grep ^name: | awk '{print $2}' )
          PROJECT_VERSION=$( ./gradlew properties |  grep ^version: | awk '{print $2}' )
          IMAGE_NAME=$DOCKER_IMAGE_PREFIX/$PROJECT_NAME:$PROJECT_VERSION
          echo $IMAGE_NAME
          echo "IMAGE_NAME=$DOCKER_IMAGE_PREFIX/$PROJECT_NAME:$PROJECT_VERSION" >> $GITHUB_ENV
        env:
          # TODO: replace with external variables
          DOCKER_IMAGE_PREFIX: europe-west1-docker.pkg.dev/vbdev-436712/lpt

      - name: Push to GAR
        run: |
          docker tag tmp $IMAGE_NAME
          docker push $IMAGE_NAME
